# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a21b194dd881d821d1f9d2b1669780cb49fe2967cb4d3e7a2f602a1cb9014e49badad8af4cffb82dfa1c3260bc10c026c69247c598c946c42e9c6a6e5e6de912

test:
  secret_key_base: 9bbbc3a234ee86491c79d36d5ff5745d9a04c3ce71d087ae34be27a65e2b00481236d8ecea779156e0b6ae3a8e974fdb6752bb365ce7c681b36c8de013ac4a7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
